[package]
name = "layerx-bridge-relayer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "layerx-bridge-relayer"
path = "src/main.rs"

[[bin]]
name = "layerx-bridge-cosign"
path = "src/bin/cosign.rs"

[dependencies]
ed25519-dalek.workspace = true
k256.workspace = true
layerx-crypto.workspace = true
layerx-mirror.workspace = true
layerx-paxeer-verifier = { path = "../../../agent/crates/layerx-paxeer-verifier" }
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sha3.workspace = true

[lints]
workspace = true
