// Command specgen compiles the IDE-neutral spec system in spec/ into:
//   - per-IDE pointer/rule files (Cursor, Windsurf, Claude, Codex, Copilot, Kiro)
//   - a human-readable markdown mirror (requirements.md / design.md / tasks.md)
//     rendered from each feature's spec.kvx
//
// The kvx files in spec/ are the SINGLE SOURCE OF TRUTH. Everything specgen
// writes is generated output — do not hand-edit it.
//
// Usage:
//
//	go run ./tools/specgen -root .          # render from the repository root
//	go run ./tools/specgen -root . -check   # fail (non-zero) if any output is stale or the spec is invalid
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

func main() {
	root := flag.String("root", "", "repository root (required)")
	check := flag.Bool("check", false, "verify outputs are up to date; exit non-zero if stale")
	flag.Parse()

	if *root == "" {
		fmt.Fprintln(os.Stderr, "specgen: -root is required")
		os.Exit(2)
	}
	repo := filepath.Clean(*root)

	w := &writer{check: *check}
	if err := run(repo, w); err != nil {
		fmt.Fprintln(os.Stderr, "specgen:", err)
		os.Exit(1)
	}
	if *check && w.stale > 0 {
		fmt.Fprintf(os.Stderr, "specgen: %d output(s) stale — run `go run ./tools/specgen -root .` and commit\n", w.stale)
		os.Exit(2)
	}
	fmt.Printf("specgen: %d written, %d unchanged%s\n", w.written, w.unchanged, checkSuffix(*check, w.stale))
}

func run(repo string, w *writer) error {
	specDir := filepath.Join(repo, "spec")
	wf, err := ParseFile(filepath.Join(specDir, "workflow.kvx"))
	if err != nil {
		return fmt.Errorf("workflow.kvx: %w", err)
	}
	banner := wf.Str("render", "banner")
	if banner == "" {
		banner = "GENERATED by tools/specgen — DO NOT EDIT."
	}

	active := wf.Str("meta", "active_feature")
	if active == "" {
		return fmt.Errorf("workflow.kvx: [meta].active_feature is empty")
	}
	fdir := filepath.Join(specDir, active)
	spec, err := ParseFile(filepath.Join(fdir, "spec.kvx"))
	if err != nil {
		return fmt.Errorf("active feature %s: %w", active, err)
	}
	if errs := Validate(wf, spec); len(errs) > 0 {
		for _, e := range errs {
			fmt.Fprintln(os.Stderr, "invalid:", e)
		}
		return fmt.Errorf("active feature %s: %d validation error(s)", active, len(errs))
	}

	// 1. Per-IDE adapter pointer files.
	brief := buildBrief(wf)
	for _, kv := range wf.OrderedKV("adapters", "") {
		label, rel := kv[0], kv[1]
		if rel == "" {
			continue
		}
		if err := w.write(filepath.Join(repo, rel), adapter(label, brief, banner)); err != nil {
			return err
		}
	}

	// 2. Markdown mirror of the active feature, only when requested.
	if wf.Bool("render", "markdown_mirror", false) {
		if err := renderFeature(repo, specDir, fdir, banner, wf.Bool("render", "mirror_to_kiro", false), w); err != nil {
			return fmt.Errorf("feature %s: %w", active, err)
		}
	}
	return nil
}

func renderFeature(repo, specDir, fdir, banner string, mirrorKiro bool, w *writer) error {
	f, err := ParseFile(filepath.Join(fdir, "spec.kvx"))
	if err != nil {
		return err
	}
	feature := f.Str("meta", "feature")
	if feature == "" {
		feature = filepath.Base(fdir)
	}

	req := renderRequirements(f, banner)
	des, err := renderDesign(f, fdir, banner)
	if err != nil {
		return err
	}
	tasks, err := renderTasks(f, fdir, banner)
	if err != nil {
		return err
	}

	out := map[string]string{
		filepath.Join(fdir, "requirements.md"): req,
		filepath.Join(fdir, "design.md"):       des,
		filepath.Join(fdir, "tasks.md"):        tasks,
	}
	if mirrorKiro {
		kdir := filepath.Join(repo, ".kiro", "specs", feature)
		out[filepath.Join(kdir, "requirements.md")] = req
		out[filepath.Join(kdir, "design.md")] = des
		out[filepath.Join(kdir, "tasks.md")] = tasks
	}

	paths := make([]string, 0, len(out))
	for p := range out {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		if err := w.write(p, out[p]); err != nil {
			return err
		}
	}
	return nil
}

// writer writes files idempotently (skips unchanged) and supports -check mode
// (reports staleness without writing).
type writer struct {
	check                     bool
	written, unchanged, stale int
}

func (w *writer) write(path, content string) error {
	old, err := os.ReadFile(path)
	if err == nil && string(old) == content {
		w.unchanged++
		return nil
	}
	if w.check {
		w.stale++
		fmt.Fprintln(os.Stderr, "stale:", path)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	w.written++
	fmt.Fprintln(os.Stderr, "wrote:", path)
	return nil
}

func checkSuffix(check bool, stale int) string {
	if check {
		return fmt.Sprintf(", %d stale", stale)
	}
	return ""
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
