// Code generated by tendermint/internal/protoutils/wireguard/plugin. DO NOT EDIT.
package blocksync

import (
	wireguard "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/internal/protoutils/wireguard"
	utils "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/libs/utils"
	types "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/proto/tendermint/types"
)

// SchemaForBlockResponse is the wireguard.Schema generated for tendermint.blocksync.BlockResponse.
var SchemaForBlockResponse = &wireguard.Schema{
	Rules: map[wireguard.Number]wireguard.Rule{
		wireguard.MustFieldNum[BlockResponse]("block"): {Nested: utils.Some(types.SchemaForBlock)},
	},
}

// SchemaForMessage is the wireguard.Schema generated for tendermint.blocksync.Message.
var SchemaForMessage = &wireguard.Schema{
	Rules: map[wireguard.Number]wireguard.Rule{
		wireguard.MustFieldNum[Message_BlockResponse]("block_response"): {Nested: utils.Some(SchemaForBlockResponse)},
	},
}

func (x *BlockResponse) WireguardScan(bz []byte) error {
	return SchemaForBlockResponse.Scan(bz)
}

func (x *Message) WireguardScan(bz []byte) error {
	return SchemaForMessage.Scan(bz)
}
