syntax = "proto3";
package paxprotocol.paxchain.epoch;

import "epoch/epoch.proto";
import "epoch/params.proto";
import "gogoproto/gogo.proto";
// this line is used by starport scaffolding # genesis/proto/import

option go_package = "github.com/Sidiora-Labs/Paxeer-X-Network/modules/epoch/types";

// GenesisState defines the epoch module's genesis state.
message GenesisState {
  Params params = 1 [(gogoproto.nullable) = false];
  Epoch epoch = 2;
  // this line is used by starport scaffolding # genesis/proto/state
}
