// Code generated by tendermint/internal/protoutils/wireguard/plugin. DO NOT EDIT.
package types

import (
	wireguard "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/internal/protoutils/wireguard"
	utils "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/libs/utils"
)

// SchemaForBlock is the wireguard.Schema generated for tendermint.types.Block.
var SchemaForBlock = &wireguard.Schema{
	Rules: map[wireguard.Number]wireguard.Rule{
		wireguard.MustFieldNum[Block]("evidence"):    {Nested: utils.Some(SchemaForEvidenceList)},
		wireguard.MustFieldNum[Block]("last_commit"): {Nested: utils.Some(SchemaForCommit)},
	},
}

func (x *Block) WireguardScan(bz []byte) error {
	return SchemaForBlock.Scan(bz)
}
