// Code generated by scripts/bump_version; DO NOT EDIT.

package solo

import (
	solov614 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/solo/legacy/v614"
	solov620 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/solo/legacy/v620"
	solov630 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/solo/legacy/v630"
	solov640 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/solo/legacy/v640"
	"github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/utils"
	"github.com/ethereum/go-ethereum/core/vm"
)

func GetVersioned(latestUpgrade string, keepers utils.Keepers) utils.VersionedPrecompiles {
	return utils.VersionedPrecompiles{
		latestUpgrade: check(NewPrecompile(keepers)),
		"v6.1.4":      check(solov614.NewPrecompile(keepers)),
		"v6.2.0":      check(solov620.NewPrecompile(keepers)),
		"v6.3.0":      check(solov630.NewPrecompile(keepers)),
		"v6.4.0":      check(solov640.NewPrecompile(keepers)),
	}
}

func check(p vm.PrecompiledContract, err error) vm.PrecompiledContract {
	if err != nil {
		panic(err)
	}
	return p
}
