services:
  prometheus:
    image: prom/prometheus:v2.55.1
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
    volumes:
      - ./rendered/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
      - ./rendered/targets:/etc/prometheus/targets:ro
      - prometheus-data:/prometheus
    ports:
      - 127.0.0.1:9090:9090

  alertmanager:
    image: prom/alertmanager:v0.27.0
    restart: unless-stopped
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    volumes:
      - ./rendered/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./rendered/secrets:/etc/alertmanager/secrets:ro
      - alertmanager-data:/alertmanager
    ports:
      - 127.0.0.1:9093:9093

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    restart: unless-stopped
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml:ro

  node-exporter:
    image: prom/node-exporter:v1.8.2
    restart: unless-stopped
    pid: host
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave

volumes:
  prometheus-data:
  alertmanager-data:
