//! Non-authoritative `LayerX` agent daemon.

pub mod admin;
pub mod agent_rpc;
pub mod agent_rpc_adapters;
mod agent_rpc_wire;
pub mod agent_rpc_dispatch;
pub mod agent_rpc_peer;
pub mod agent_rpc_tls;
pub mod approval;
pub mod audit;
pub mod authority;
pub mod boot;
pub mod budget;
pub mod cache;
pub mod capability;
pub mod compat;
pub mod config;
pub mod degraded;
pub mod enrolment;
pub mod events;
pub mod export;
pub mod finality;
pub mod human;
pub mod human_runtime;
pub mod idempotency;
pub mod identity;
pub mod limits;
pub mod managed_agent;
pub mod obs;
pub mod ops;
pub mod outbox;
pub mod policy;
pub mod prepare;
pub mod protocol_evidence;
pub mod read;
pub mod receipt;
pub mod session;
pub mod session_control;
pub mod session_keys;
pub mod shutdown;
pub mod sign;
pub mod store;
pub mod tenant;

mod outbound_tls;
