*
!explorer/services/smart-contract-verifier
explorer/services/smart-contract-verifier/target
explorer/services/smart-contract-verifier/*-compilers
explorer/services/smart-contract-verifier/README.md
explorer/services/smart-contract-verifier/tests
explorer/services/smart-contract-verifier/config.toml
