[package]
name = "layerx-agent-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
layerx-types = { path = "../layerx-types" }
layerx-client = { path = "../layerx-client" }
layerx-proof = { path = "../layerx-proof" }

[lints]
workspace = true
