/**
 * Environment variable schema and validation
 */

export const DEFAULT_EXPLORER_BASE = 'https://paxscan.io';
export const DEFAULT_BLOCKSCOUT_UPSTREAM_BASE = 'https://api.paxscan.io';

export interface EnvSchema {
  // API Keys
  NEXT_PUBLIC_SENTRY_DSN?: string;
  SENTRY_DSN?: string;

  // RPC URLs
  NEXT_PUBLIC_PAXEER_RPC_URL?: string;
  NEXT_PUBLIC_CHAIN_ID?: string;

  // Gas station
  NEXT_PUBLIC_PAXEER_WALLET_API?: string;
  NEXT_PUBLIC_PAXEER_GAS_SPONSOR?: string;
  NEXT_PUBLIC_PAXEER_GAS_PAYMASTER?: string;
  NEXT_PUBLIC_PAXEER_USID_PER_PAX?: string;
  NEXT_PUBLIC_SID?: string;

  // Explorer
  NEXT_PUBLIC_PAXEER_EXPLORER_URL: string;
  NEXT_PUBLIC_EXPLORER_BASE: string;
  BLOCKSCOUT_UPSTREAM_BASE: string;

  // Push
  NEXT_PUBLIC_VAPID_PUBLIC_KEY?: string;

  // Feature Flags
  NEXT_PUBLIC_ENABLE_TESTNETS?: string;
  NEXT_PUBLIC_ENABLE_ANALYTICS?: string;

  // External APIs
  NEXT_PUBLIC_SIDIORA_API_URL?: string;
  NEXT_PUBLIC_CROSSVERSE_API_URL?: string;
  NEXT_PUBLIC_BLOCKSCOUT_API_URL?: string;

  // Build
  NODE_ENV?: 'development' | 'production' | 'test';
}

export function validateEnv(source: Record<string, string | undefined> = process.env): EnvSchema {
  const env: EnvSchema = {
    NEXT_PUBLIC_SENTRY_DSN: source.NEXT_PUBLIC_SENTRY_DSN,
    SENTRY_DSN: source.SENTRY_DSN,
    NEXT_PUBLIC_PAXEER_RPC_URL: source.NEXT_PUBLIC_PAXEER_RPC_URL,
    NEXT_PUBLIC_CHAIN_ID: source.NEXT_PUBLIC_CHAIN_ID,
    NEXT_PUBLIC_PAXEER_WALLET_API: source.NEXT_PUBLIC_PAXEER_WALLET_API,
    NEXT_PUBLIC_PAXEER_GAS_SPONSOR: source.NEXT_PUBLIC_PAXEER_GAS_SPONSOR,
    NEXT_PUBLIC_PAXEER_GAS_PAYMASTER: source.NEXT_PUBLIC_PAXEER_GAS_PAYMASTER,
    NEXT_PUBLIC_PAXEER_USID_PER_PAX: source.NEXT_PUBLIC_PAXEER_USID_PER_PAX,
    NEXT_PUBLIC_SID: source.NEXT_PUBLIC_SID,
    NEXT_PUBLIC_PAXEER_EXPLORER_URL: source.NEXT_PUBLIC_PAXEER_EXPLORER_URL || DEFAULT_EXPLORER_BASE,
    NEXT_PUBLIC_EXPLORER_BASE: source.NEXT_PUBLIC_EXPLORER_BASE || DEFAULT_EXPLORER_BASE,
    BLOCKSCOUT_UPSTREAM_BASE: source.BLOCKSCOUT_UPSTREAM_BASE || DEFAULT_BLOCKSCOUT_UPSTREAM_BASE,
    NEXT_PUBLIC_VAPID_PUBLIC_KEY: source.NEXT_PUBLIC_VAPID_PUBLIC_KEY,
    NEXT_PUBLIC_ENABLE_TESTNETS: source.NEXT_PUBLIC_ENABLE_TESTNETS,
    NEXT_PUBLIC_ENABLE_ANALYTICS: source.NEXT_PUBLIC_ENABLE_ANALYTICS,
    NEXT_PUBLIC_SIDIORA_API_URL: source.NEXT_PUBLIC_SIDIORA_API_URL,
    NEXT_PUBLIC_CROSSVERSE_API_URL: source.NEXT_PUBLIC_CROSSVERSE_API_URL,
    NEXT_PUBLIC_BLOCKSCOUT_API_URL: source.NEXT_PUBLIC_BLOCKSCOUT_API_URL,
    NODE_ENV: source.NODE_ENV as EnvSchema['NODE_ENV'],
  };

  // Add validation logic as needed

  return env;
}

export const env = validateEnv();
