// Code generated from the LayerX Agent API and Human API schemas. DO NOT EDIT.

package com.sidiora.layerx.sdk;

import java.util.List;
import java.util.Map;
import java.util.Set;

final class GeneratedContract {
    private GeneratedContract() {}
    static final Set<String> AGENT_OPERATIONS = Set.of(
        "agent.register",
        "approval.approve",
        "approval.get",
        "approval.list",
        "approval.reject",
        "availability.fetch",
        "budget.create",
        "budget.fund",
        "budget.list",
        "budget.reconciliation",
        "budget.revoke",
        "budget.state",
        "capability.attenuate",
        "capability.create",
        "capability.list",
        "capability.revoke",
        "export.offline",
        "faucet.claim",
        "policy.dry_run",
        "prepare",
        "program.activity",
        "program.call",
        "program.deploy",
        "program.discover",
        "program.interface",
        "program.receipt",
        "program.simulate",
        "program.upgrade",
        "program.wind-down",
        "project",
        "read.account",
        "read.balance",
        "read.batch",
        "read.checkpoint",
        "read.history",
        "read.module_state",
        "read.proof_bundle",
        "session.close",
        "session.list",
        "session.open",
        "session.refresh",
        "sign",
        "submit",
        "subscription.acknowledge",
        "subscription.create",
        "subscription.delete",
        "subscription.health",
        "subscription.list",
        "subscription.pause",
        "subscription.resume",
        "track",
        "wait");
    static final Set<String> AGENT_IDEMPOTENT = Set.of(
        "agent.register",
        "approval.approve",
        "approval.reject",
        "budget.create",
        "budget.fund",
        "budget.revoke",
        "capability.attenuate",
        "capability.create",
        "capability.revoke",
        "prepare",
        "program.call",
        "program.deploy",
        "program.upgrade",
        "program.wind-down",
        "session.close",
        "session.open",
        "session.refresh",
        "sign",
        "submit",
        "subscription.acknowledge",
        "subscription.create",
        "subscription.delete",
        "subscription.pause",
        "subscription.resume");
    static final Set<String> AGENT_ERROR_CLASSES = Set.of(
        "TransportFailure",
        "Deadline",
        "ProtocolIncompatibility",
        "UnavailableCapability",
        "CoreRejection",
        "VerificationFailure",
        "PolicyRefusal",
        "CapabilityRefusal",
        "BudgetRefusal",
        "RateLimit",
        "IdempotencyConflict",
        "InternalFault");
    static final Set<String> AGENT_RETRIABILITY = Set.of(
        "Terminal",
        "Retriable");
    static final Set<String> HUMAN_ERROR_CODES = Set.of(
        "unauthenticated",
        "session-expired",
        "step-up-required",
        "forbidden",
        "not-found",
        "invalid-request",
        "conflict",
        "rate-limited",
        "cursor-expired",
        "unavailable",
        "upstream-degraded",
        "challenge-expired",
        "refused-by-policy",
        "refused-by-budget",
        "refused-by-capability",
        "refused-by-protocol",
        "refused-by-limit",
        "quote-expired",
        "wallet-not-bound",
        "exit-unavailable",
        "already-decided",
        "hold-expired",
        "hold-defective",
        "archive-needs-disposition",
        "confirmation-mismatch",
        "not-suppressible",
        "support-unavailable",
        "support-conversation-unknown",
        "support-message-unknown");
    static final Set<String> HUMAN_RETRIABILITY = Set.of(
        "retriable",
        "retriable-after",
        "structural",
        "final");
    static final Map<String, OperationCatalog.Route> HUMAN_ROUTES = Map.ofEntries(
        Map.entry("account.balance", new OperationCatalog.Route("GET", "/v1/account/balance", List.of(), false, true)),
        Map.entry("account.create", new OperationCatalog.Route("POST", "/v1/accounts", List.of(), true, false)),
        Map.entry("activity.entry", new OperationCatalog.Route("GET", "/v1/activity/{entry_id}", List.of("entry_id"), false, true)),
        Map.entry("activity.export.evidence", new OperationCatalog.Route("POST", "/v1/activity/exports/evidence", List.of(), true, false)),
        Map.entry("activity.export.statement", new OperationCatalog.Route("POST", "/v1/activity/exports/statement", List.of(), true, false)),
        Map.entry("activity.query", new OperationCatalog.Route("POST", "/v1/activity/query", List.of(), false, false)),
        Map.entry("agent.archive", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/archive", List.of("agent_id"), true, false)),
        Map.entry("agent.create", new OperationCatalog.Route("POST", "/v1/agents", List.of(), true, false)),
        Map.entry("agent.get", new OperationCatalog.Route("GET", "/v1/agents/{agent_id}", List.of("agent_id"), false, true)),
        Map.entry("agent.limit", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/limit", List.of("agent_id"), true, false)),
        Map.entry("agent.list", new OperationCatalog.Route("GET", "/v1/agents", List.of(), false, true)),
        Map.entry("agent.pause", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/pause", List.of("agent_id"), true, true)),
        Map.entry("agent.reclaim", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/reclaim", List.of("agent_id"), true, false)),
        Map.entry("agent.recover", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/recover", List.of("agent_id"), true, true)),
        Map.entry("agent.resume", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/resume", List.of("agent_id"), true, true)),
        Map.entry("agent.rotate", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/rotate", List.of("agent_id"), true, true)),
        Map.entry("agent.rotation.disclosure", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/rotation/disclosure", List.of("agent_id"), false, false)),
        Map.entry("agent.rotation.start", new OperationCatalog.Route("POST", "/v1/agents/{agent_id}/rotation", List.of("agent_id"), true, false)),
        Map.entry("approval.approve", new OperationCatalog.Route("POST", "/v1/approvals/{approval_id}/approve", List.of("approval_id"), true, false)),
        Map.entry("approval.get", new OperationCatalog.Route("GET", "/v1/approvals/{approval_id}", List.of("approval_id"), false, true)),
        Map.entry("approval.list", new OperationCatalog.Route("GET", "/v1/approvals", List.of(), false, true)),
        Map.entry("approval.reject", new OperationCatalog.Route("POST", "/v1/approvals/{approval_id}/reject", List.of("approval_id"), true, true)),
        Map.entry("authenticator.backup.rotate", new OperationCatalog.Route("POST", "/v1/security/authenticators/backup-codes", List.of(), false, false)),
        Map.entry("authenticator.disable", new OperationCatalog.Route("POST", "/v1/security/authenticators/{authenticator_id}/disable", List.of("authenticator_id"), false, false)),
        Map.entry("authenticator.setup.begin", new OperationCatalog.Route("POST", "/v1/security/authenticators/setups", List.of(), false, false)),
        Map.entry("authenticator.setup.finish", new OperationCatalog.Route("POST", "/v1/security/authenticators/setups/{setup_id}", List.of("setup_id"), false, false)),
        Map.entry("authenticator.status", new OperationCatalog.Route("GET", "/v1/security/authenticators", List.of(), false, true)),
        Map.entry("binding.rebind", new OperationCatalog.Route("POST", "/v1/wallet-binding/rebind", List.of(), true, false)),
        Map.entry("binding.rebind.action", new OperationCatalog.Route("POST", "/v1/wallet-binding/rebind/action", List.of(), false, false)),
        Map.entry("binding.statement", new OperationCatalog.Route("POST", "/v1/wallet-binding/statement", List.of(), false, false)),
        Map.entry("binding.status", new OperationCatalog.Route("GET", "/v1/wallet-binding", List.of(), false, true)),
        Map.entry("binding.submit", new OperationCatalog.Route("POST", "/v1/wallet-binding", List.of(), true, false)),
        Map.entry("deposit.confirm", new OperationCatalog.Route("POST", "/v1/deposits/{journey_id}/confirm", List.of("journey_id"), false, false)),
        Map.entry("deposit.start", new OperationCatalog.Route("POST", "/v1/deposits", List.of(), true, false)),
        Map.entry("evidence.get", new OperationCatalog.Route("GET", "/v1/evidence/{evidence_id}", List.of("evidence_id"), false, true)),
        Map.entry("exit.eligibility", new OperationCatalog.Route("GET", "/v1/exit/eligibility", List.of(), false, true)),
        Map.entry("exit.start", new OperationCatalog.Route("POST", "/v1/exit", List.of(), true, false)),
        Map.entry("home.summary", new OperationCatalog.Route("GET", "/v1/home", List.of(), false, true)),
        Map.entry("intent.plan", new OperationCatalog.Route("POST", "/v1/intents/plan", List.of(), false, false)),
        Map.entry("intent.submit", new OperationCatalog.Route("POST", "/v1/intents/submit", List.of(), true, false)),
        Map.entry("journey.get", new OperationCatalog.Route("GET", "/v1/journeys/{journey_id}", List.of("journey_id"), false, true)),
        Map.entry("journey.list", new OperationCatalog.Route("GET", "/v1/journeys", List.of(), false, true)),
        Map.entry("move.commit", new OperationCatalog.Route("POST", "/v1/moves", List.of(), true, false)),
        Map.entry("move.quote", new OperationCatalog.Route("POST", "/v1/moves/quote", List.of(), false, false)),
        Map.entry("notification.list", new OperationCatalog.Route("GET", "/v1/notifications", List.of(), false, true)),
        Map.entry("notification.preferences.get", new OperationCatalog.Route("GET", "/v1/notifications/preferences", List.of(), false, true)),
        Map.entry("notification.preferences.set", new OperationCatalog.Route("POST", "/v1/notifications/preferences", List.of(), false, false)),
        Map.entry("notification.read", new OperationCatalog.Route("POST", "/v1/notifications/{notification_id}/read", List.of("notification_id"), false, true)),
        Map.entry("onboarding.resume", new OperationCatalog.Route("POST", "/v1/onboarding/resume", List.of(), false, true)),
        Map.entry("onboarding.status", new OperationCatalog.Route("GET", "/v1/onboarding", List.of(), false, true)),
        Map.entry("passkey.assert.begin", new OperationCatalog.Route("POST", "/v1/passkeys/assertions", List.of(), false, false)),
        Map.entry("passkey.assert.finish", new OperationCatalog.Route("POST", "/v1/passkeys/assertions/{assertion_id}", List.of("assertion_id"), false, false)),
        Map.entry("passkey.register.begin", new OperationCatalog.Route("POST", "/v1/passkeys/registrations", List.of(), false, false)),
        Map.entry("passkey.register.finish", new OperationCatalog.Route("POST", "/v1/passkeys/registrations/{registration_id}", List.of("registration_id"), false, false)),
        Map.entry("profile.get", new OperationCatalog.Route("GET", "/v1/profile", List.of(), false, true)),
        Map.entry("profile.update", new OperationCatalog.Route("PATCH", "/v1/profile", List.of(), false, false)),
        Map.entry("security.action", new OperationCatalog.Route("POST", "/v1/security/actions", List.of(), false, false)),
        Map.entry("security.key-export.begin", new OperationCatalog.Route("POST", "/v1/security/key-export/begin", List.of(), false, false)),
        Map.entry("security.key-export.finish", new OperationCatalog.Route("POST", "/v1/security/key-export/finish", List.of(), false, false)),
        Map.entry("security.passkey.list", new OperationCatalog.Route("GET", "/v1/security/passkeys", List.of(), false, true)),
        Map.entry("security.passkey.register.begin", new OperationCatalog.Route("POST", "/v1/security/passkeys/registrations", List.of(), false, false)),
        Map.entry("security.passkey.register.finish", new OperationCatalog.Route("POST", "/v1/security/passkeys/registrations/{registration_id}", List.of("registration_id"), false, false)),
        Map.entry("security.passkey.revoke", new OperationCatalog.Route("POST", "/v1/security/passkeys/{passkey_id}/revoke", List.of("passkey_id"), false, false)),
        Map.entry("security.recovery.reveal", new OperationCatalog.Route("POST", "/v1/security/recovery/evidence", List.of(), false, false)),
        Map.entry("security.session.revoke", new OperationCatalog.Route("POST", "/v1/security/sessions/{session_id}/revoke", List.of("session_id"), true, false)),
        Map.entry("security.session.revoke-all", new OperationCatalog.Route("POST", "/v1/security/sessions/revoke-all", List.of(), true, false)),
        Map.entry("session.fee-policy", new OperationCatalog.Route("GET", "/v1/sessions/fee-policy", List.of(), false, true)),
        Map.entry("session.list", new OperationCatalog.Route("GET", "/v1/sessions", List.of(), false, true)),
        Map.entry("session.open", new OperationCatalog.Route("POST", "/v1/sessions", List.of(), true, false)),
        Map.entry("session.refresh", new OperationCatalog.Route("POST", "/v1/sessions/refresh", List.of(), false, true)),
        Map.entry("session.revoke", new OperationCatalog.Route("DELETE", "/v1/sessions/{session_id}", List.of("session_id"), true, true)),
        Map.entry("session.revoke-all", new OperationCatalog.Route("POST", "/v1/sessions/revoke-all", List.of(), true, true)),
        Map.entry("stepup.begin", new OperationCatalog.Route("POST", "/v1/step-up", List.of(), false, false)),
        Map.entry("stepup.finish", new OperationCatalog.Route("POST", "/v1/step-up/{challenge_id}", List.of("challenge_id"), false, false)),
        Map.entry("stream.next", new OperationCatalog.Route("GET", "/v1/stream/{cursor}", List.of("cursor"), false, true)),
        Map.entry("stream.open", new OperationCatalog.Route("POST", "/v1/stream", List.of(), false, true)),
        Map.entry("support.create", new OperationCatalog.Route("POST", "/v1/support/conversations", List.of(), true, false)),
        Map.entry("support.feedback", new OperationCatalog.Route("POST", "/v1/support/conversations/{conversation_id}/feedback", List.of("conversation_id"), false, false)),
        Map.entry("support.list", new OperationCatalog.Route("GET", "/v1/support/conversations", List.of(), false, true)),
        Map.entry("support.read", new OperationCatalog.Route("POST", "/v1/support/conversations/{conversation_id}/read", List.of("conversation_id"), false, false)),
        Map.entry("support.reply", new OperationCatalog.Route("POST", "/v1/support/conversations/{conversation_id}/replies", List.of("conversation_id"), true, false)),
        Map.entry("support.status", new OperationCatalog.Route("GET", "/v1/support/conversations/{conversation_id}/status", List.of("conversation_id"), false, true)),
        Map.entry("version", new OperationCatalog.Route("GET", "/v1/version", List.of(), false, true)),
        Map.entry("withdraw.claim", new OperationCatalog.Route("POST", "/v1/withdrawals/{journey_id}/claim", List.of("journey_id"), false, false)),
        Map.entry("withdraw.start", new OperationCatalog.Route("POST", "/v1/withdrawals", List.of(), true, false)));
}
