// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layerxexchange/params.proto

package types

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Market is one LayerX perps market Paxeer accepts order intents for.
// Identifiers are 64 lowercase hex characters.
type Market struct {
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// margin_asset_id is the custody asset margin for this market is held in.
	MarginAssetId     string `protobuf:"bytes,2,opt,name=margin_asset_id,json=marginAssetId,proto3" json:"margin_asset_id,omitempty"`
	Enabled           bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	NativeGenesis     []byte `protobuf:"bytes,4,opt,name=native_genesis,json=nativeGenesis,proto3" json:"native_genesis,omitempty"`
	CapabilityBatch   uint64 `protobuf:"varint,5,opt,name=capability_batch,json=capabilityBatch,proto3" json:"capability_batch,omitempty"`
	CapabilityWitness []byte `protobuf:"bytes,6,opt,name=capability_witness,json=capabilityWitness,proto3" json:"capability_witness,omitempty"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7935f8001d7ad91, []int{0}
}
func (m *Market) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Market.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return m.Size()
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *Market) GetMarginAssetId() string {
	if m != nil {
		return m.MarginAssetId
	}
	return ""
}

func (m *Market) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Market) GetNativeGenesis() []byte {
	if m != nil {
		return m.NativeGenesis
	}
	return nil
}

func (m *Market) GetCapabilityBatch() uint64 {
	if m != nil {
		return m.CapabilityBatch
	}
	return 0
}

func (m *Market) GetCapabilityWitness() []byte {
	if m != nil {
		return m.CapabilityWitness
	}
	return nil
}

// Params defines the parameters of the layerxexchange module.
type Params struct {
	// authority is the bech32 account allowed to change params. Empty selects
	// the governance module account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// markets are the markets placeOrder accepts. Matching happens on LayerX.
	Markets []Market `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7935f8001d7ad91, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Params) GetMarkets() []Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

func init() {
	proto.RegisterType((*Market)(nil), "paxprotocol.paxchain.layerxexchange.Market")
	proto.RegisterType((*Params)(nil), "paxprotocol.paxchain.layerxexchange.Params")
}

func init() { proto.RegisterFile("layerxexchange/params.proto", fileDescriptor_b7935f8001d7ad91) }

var fileDescriptor_b7935f8001d7ad91 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x33, 0xf7, 0xc6, 0xdc, 0xdb, 0xd1, 0x5a, 0x1d, 0x5c, 0x04, 0x2b, 0x69, 0xa8, 0x28,
	0x11, 0x69, 0x02, 0xba, 0x73, 0x67, 0x5d, 0x48, 0x11, 0x41, 0xb2, 0x11, 0x04, 0x09, 0x27, 0xc9,
	0x90, 0x0c, 0x4d, 0x66, 0xc2, 0xcc, 0xd4, 0x26, 0x6f, 0xe1, 0x23, 0xf8, 0x38, 0x5d, 0x76, 0xe9,
	0x4a, 0xa4, 0xdd, 0xb8, 0xf2, 0x19, 0x24, 0x19, 0x4b, 0xd5, 0x95, 0xbb, 0x7f, 0xbe, 0xf3, 0x9f,
	0xc3, 0x9c, 0x9f, 0x83, 0xa7, 0x15, 0x74, 0x54, 0xb6, 0xb4, 0xcd, 0x4a, 0xe0, 0x05, 0x8d, 0x1a,
	0x90, 0x50, 0xab, 0xb0, 0x91, 0x42, 0x0b, 0xf2, 0xb0, 0x81, 0x76, 0x50, 0x99, 0xa8, 0xc2, 0x06,
	0x7a, 0x0f, 0xe3, 0xe1, 0xdf, 0x1d, 0xf7, 0xef, 0x15, 0xa2, 0x10, 0x83, 0x2b, 0xea, 0x95, 0x69,
	0x9d, 0xff, 0x44, 0xd8, 0x79, 0x0b, 0x72, 0x4d, 0x35, 0x99, 0xe2, 0x51, 0x3d, 0xa8, 0x84, 0xe5,
	0x2e, 0xf2, 0x51, 0x30, 0x8a, 0xaf, 0x0d, 0x58, 0xe5, 0xe4, 0x31, 0x9e, 0xd4, 0x20, 0x0b, 0xc6,
	0x13, 0x50, 0xca, 0x58, 0x2e, 0x06, 0xcb, 0xd8, 0xe0, 0x97, 0x3d, 0x5d, 0xe5, 0xc4, 0xc5, 0x57,
	0x94, 0x43, 0x5a, 0xd1, 0xdc, 0xbd, 0xf4, 0x51, 0x70, 0x1d, 0x9f, 0x9e, 0xe4, 0x11, 0xbe, 0xcd,
	0x41, 0xb3, 0x4f, 0x34, 0x29, 0x28, 0xa7, 0x8a, 0x29, 0xd7, 0xf6, 0x51, 0x70, 0x2b, 0x1e, 0x1b,
	0xfa, 0xda, 0x40, 0xf2, 0x04, 0xdf, 0xc9, 0xa0, 0x81, 0x94, 0x55, 0x4c, 0x77, 0x49, 0x0a, 0x3a,
	0x2b, 0xdd, 0x1b, 0x3e, 0x0a, 0xec, 0x78, 0x72, 0xe6, 0xcb, 0x1e, 0x93, 0x05, 0x26, 0x7f, 0x58,
	0xb7, 0x4c, 0x73, 0xaa, 0x94, 0xeb, 0x0c, 0x53, 0xef, 0x9e, 0x2b, 0xef, 0x4d, 0xe1, 0x85, 0xfd,
	0xe3, 0xcb, 0x0c, 0xcd, 0x15, 0x76, 0xde, 0x0d, 0xd9, 0x91, 0x07, 0x78, 0x04, 0x1b, 0x5d, 0x0a,
	0xc9, 0x74, 0xf7, 0x7b, 0xdf, 0x33, 0x20, 0x6f, 0xf0, 0x95, 0x59, 0x5e, 0xb9, 0x17, 0xfe, 0x65,
	0x70, 0xf3, 0xd9, 0xd3, 0xf0, 0x3f, 0x52, 0x0e, 0x4d, 0x96, 0x4b, 0x7b, 0xf7, 0x6d, 0x66, 0xc5,
	0xa7, 0x09, 0xcb, 0x8f, 0xbb, 0x83, 0x87, 0xf6, 0x07, 0x0f, 0x7d, 0x3f, 0x78, 0xe8, 0xf3, 0xd1,
	0xb3, 0xf6, 0x47, 0xcf, 0xfa, 0x7a, 0xf4, 0xac, 0x0f, 0xaf, 0x0a, 0xa6, 0xcb, 0x4d, 0x1a, 0x66,
	0xa2, 0x8e, 0x14, 0xcb, 0x99, 0x90, 0xb0, 0xa8, 0x20, 0x55, 0x51, 0x03, 0x2d, 0xa5, 0x72, 0xc1,
	0xa9, 0xde, 0x0a, 0xb9, 0x8e, 0x6a, 0x91, 0x6f, 0x2a, 0xaa, 0xa2, 0x7f, 0xce, 0x40, 0x77, 0x0d,
	0x55, 0xa9, 0x33, 0x7c, 0xeb, 0xf9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x54, 0x91, 0x7e,
	0x25, 0x02, 0x00, 0x00,
}

func (this *Market) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Market)
	if !ok {
		that2, ok := that.(Market)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MarketId != that1.MarketId {
		return false
	}
	if this.MarginAssetId != that1.MarginAssetId {
		return false
	}
	if this.Enabled != that1.Enabled {
		return false
	}
	if !bytes.Equal(this.NativeGenesis, that1.NativeGenesis) {
		return false
	}
	if this.CapabilityBatch != that1.CapabilityBatch {
		return false
	}
	if !bytes.Equal(this.CapabilityWitness, that1.CapabilityWitness) {
		return false
	}
	return true
}
func (m *Market) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Market) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Market) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CapabilityWitness) > 0 {
		i -= len(m.CapabilityWitness)
		copy(dAtA[i:], m.CapabilityWitness)
		i = encodeVarintParams(dAtA, i, uint64(len(m.CapabilityWitness)))
		i--
		dAtA[i] = 0x32
	}
	if m.CapabilityBatch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CapabilityBatch))
		i--
		dAtA[i] = 0x28
	}
	if len(m.NativeGenesis) > 0 {
		i -= len(m.NativeGenesis)
		copy(dAtA[i:], m.NativeGenesis)
		i = encodeVarintParams(dAtA, i, uint64(len(m.NativeGenesis)))
		i--
		dAtA[i] = 0x22
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.MarginAssetId) > 0 {
		i -= len(m.MarginAssetId)
		copy(dAtA[i:], m.MarginAssetId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MarginAssetId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MarketId) > 0 {
		i -= len(m.MarketId)
		copy(dAtA[i:], m.MarketId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MarketId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Markets) > 0 {
		for iNdEx := len(m.Markets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Markets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Market) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MarketId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MarginAssetId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	l = len(m.NativeGenesis)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.CapabilityBatch != 0 {
		n += 1 + sovParams(uint64(m.CapabilityBatch))
	}
	l = len(m.CapabilityWitness)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if len(m.Markets) > 0 {
		for _, e := range m.Markets {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Market) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Market: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Market: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarginAssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarginAssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeGenesis", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NativeGenesis = append(m.NativeGenesis[:0], dAtA[iNdEx:postIndex]...)
			if m.NativeGenesis == nil {
				m.NativeGenesis = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapabilityBatch", wireType)
			}
			m.CapabilityBatch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CapabilityBatch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapabilityWitness", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CapabilityWitness = append(m.CapabilityWitness[:0], dAtA[iNdEx:postIndex]...)
			if m.CapabilityWitness == nil {
				m.CapabilityWitness = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Markets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Markets = append(m.Markets, Market{})
			if err := m.Markets[len(m.Markets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
