app = "paxeer-shared-endpoint-redis"
primary_region = "ams"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[build]
  image = "redis:7.4-alpine"

[processes]
  app = "redis-server /run/secrets/redis.conf"

[[mounts]]
  source = "redis_data"
  destination = "/data"

[[files]]
  guest_path = "/run/secrets/redis.conf"
  secret_name = "REDIS_CONF"

[[files]]
  guest_path = "/run/secrets/redis.crt"
  secret_name = "REDIS_TLS_CERT"

[[files]]
  guest_path = "/run/secrets/redis.key"
  secret_name = "REDIS_TLS_KEY"

[[files]]
  guest_path = "/run/secrets/ca.crt"
  secret_name = "REDIS_TLS_CA"

[[files]]
  guest_path = "/run/secrets/users.acl"
  secret_name = "REDIS_ACL"

[[vm]]
  size = "performance-2x"
  memory = "4gb"
  cpus = 2
  cpu_kind = "performance"
