// Auto-generated by paxeer-spot-integration-kit — DO NOT EDIT.
// Contract: PECOROrders
// Source:   ../../spot/out/PECOROrders.sol/PECOROrders.json

export const PECOR_ORDERS_ABI = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_priceOracle',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_vault',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_transactionTracker',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'BPS_DENOMINATOR',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'MAX_ORDER_FEE_BPS',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'accumulatedFees',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'activeLimitOrderIds',
    inputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'batchExecuteLimitOrders',
    inputs: [
      {
        name: 'orderIds',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    outputs: [
      {
        name: 'executedCount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'batchExpireOrders',
    inputs: [
      {
        name: 'orderIds',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    outputs: [
      {
        name: 'expiredCount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'canExecuteLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      },
      {
        name: '',
        type: 'string',
        internalType: 'string'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'cancelLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'collectFees',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'executeLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'feeCollector',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'fillQualityTwapPeriod',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getAccumulatedFees',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getActiveLimitOrderCount',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getExecutableLimitOrders',
    inputs: [
      {
        name: 'maxCount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderIds',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct PECOROrders.LimitOrder',
        components: [
          {
            name: 'id',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'user',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'stablecoin',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'token',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'amount',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'targetPrice',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'orderType',
            type: 'uint8',
            internalType: 'enum PECOROrders.OrderType'
          },
          {
            name: 'status',
            type: 'uint8',
            internalType: 'enum PECOROrders.OrderStatus'
          },
          {
            name: 'createdAt',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'expiresAt',
            type: 'uint256',
            internalType: 'uint256'
          }
        ]
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getUserLimitOrders',
    inputs: [
      {
        name: 'user',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'keepers',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'limitOrders',
    inputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'user',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'targetPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'orderType',
        type: 'uint8',
        internalType: 'enum PECOROrders.OrderType'
      },
      {
        name: 'status',
        type: 'uint8',
        internalType: 'enum PECOROrders.OrderStatus'
      },
      {
        name: 'createdAt',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'modifyLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'newTargetPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'newExpiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'nextOrderId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'orderFeeBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'placeLimitBuy',
    inputs: [
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoinAmount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'targetPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'placeLimitSell',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenAmount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'targetPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'priceOracle',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPriceOracle'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setFeeCollector',
    inputs: [
      {
        name: '_collector',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setFillQualityTwapPeriod',
    inputs: [
      {
        name: 'period',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setKeeper',
    inputs: [
      {
        name: 'keeper',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'authorized',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setOrderFee',
    inputs: [
      {
        name: '_feeBps',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setPriceOracle',
    inputs: [
      {
        name: '_oracle',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setTransactionTracker',
    inputs: [
      {
        name: '_t',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'transactionTracker',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract ITransactionTracker'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      {
        name: 'newOwner',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'userLimitOrders',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPECORVault'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'event',
    name: 'LimitOrderCancelled',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'LimitOrderCreated',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'orderType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PECOROrders.OrderType'
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'targetPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'LimitOrderExecuted',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'executionPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'LimitOrderExpired',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'LimitOrderModified',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'targetPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'error',
    name: 'CannotCancel',
    inputs: []
  },
  {
    type: 'error',
    name: 'EnforcedPause',
    inputs: []
  },
  {
    type: 'error',
    name: 'ExpectedPause',
    inputs: []
  },
  {
    type: 'error',
    name: 'FeeExceedsMax',
    inputs: []
  },
  {
    type: 'error',
    name: 'InsufficientLiquidity',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidExpiry',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidOracle',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidPrice',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidTWAPPeriod',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidVault',
    inputs: []
  },
  {
    type: 'error',
    name: 'NoFeesToCollect',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotAStablecoin',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotAuthorized',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotFeeCollector',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotOrderOwner',
    inputs: []
  },
  {
    type: 'error',
    name: 'OrderExpired',
    inputs: []
  },
  {
    type: 'error',
    name: 'OrderNotPending',
    inputs: []
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [
      {
        name: 'account',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'PriceAboveTarget',
    inputs: []
  },
  {
    type: 'error',
    name: 'PriceBelowTarget',
    inputs: []
  },
  {
    type: 'error',
    name: 'ReentrancyGuardReentrantCall',
    inputs: []
  },
  {
    type: 'error',
    name: 'SameToken',
    inputs: []
  },
  {
    type: 'error',
    name: 'TokenIsStablecoin',
    inputs: []
  },
  {
    type: 'error',
    name: 'TokenPaused',
    inputs: []
  },
  {
    type: 'error',
    name: 'ZeroAmount',
    inputs: []
  }
] as const;
