// Auto-generated by paxeer-spot-integration-kit — DO NOT EDIT.
// Contract: PECOR
// Source:   ../../spot/out/PECOR.sol/PECOR.json

export const PECOR_ABI = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_priceOracle',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_vault',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_weth',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_transactionTracker',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'receive',
    stateMutability: 'payable'
  },
  {
    type: 'function',
    name: 'BPS_DENOMINATOR',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'MAX_FEE_BPS',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'MAX_IMPACT_BPS',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'PRECISION',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'TIER1_THRESHOLD',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'TIER2_THRESHOLD',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'WETH',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IWETH'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'accumulatedFees',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'collectFees',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'feeCollector',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getAccumulatedFees',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getDetailedQuote',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'grossOut',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'netOut',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'priceImpactBps',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'feeBps',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'feeAmount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getQuoteExactIn',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'amountOut',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getQuoteExactOut',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountOut',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'impactScalarBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'marketBuy',
    inputs: [
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoinAmount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'minTokenAmount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'deadline',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'tokenAmount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'marketSell',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenAmount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'minStablecoinAmount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'deadline',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'stablecoinAmount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'maxTwapDeviationBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [
      {
        name: 'data',
        type: 'bytes[]',
        internalType: 'bytes[]'
      }
    ],
    outputs: [
      {
        name: 'results',
        type: 'bytes[]',
        internalType: 'bytes[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'priceImpactEnabled',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'priceOracle',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPriceOracle'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setFeeCollector',
    inputs: [
      {
        name: '_collector',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setPriceImpact',
    inputs: [
      {
        name: '_enabled',
        type: 'bool',
        internalType: 'bool'
      },
      {
        name: '_scalarBps',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setPriceOracle',
    inputs: [
      {
        name: '_oracle',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setSwapFee',
    inputs: [
      {
        name: '_feeBps',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setTieredFees',
    inputs: [
      {
        name: '_tier1FeeBps',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: '_tier2FeeBps',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setTransactionTracker',
    inputs: [
      {
        name: '_tracker',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setTwapSanity',
    inputs: [
      {
        name: 'enabled',
        type: 'bool',
        internalType: 'bool'
      },
      {
        name: 'period',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'maxDeviationBps_',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'swapExactIn',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'amountOutMin',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'deadline',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'amountOut',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'swapExactInNative',
    inputs: [
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountOutMin',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'deadline',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'amountOut',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'payable'
  },
  {
    type: 'function',
    name: 'swapExactInToNative',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'amountOutMin',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'deadline',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'amountOut',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'swapExactOut',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountOut',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'amountInMax',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'deadline',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'swapFeeBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'tier1FeeBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'tier2FeeBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'transactionTracker',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract ITransactionTracker'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      {
        name: 'newOwner',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'twapSanityEnabled',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'twapSanityPeriod',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPECORVault'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'event',
    name: 'MarketOrderExecuted',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'token',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'stablecoinAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'tokenAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'isBuy',
        type: 'bool',
        indexed: false,
        internalType: 'bool'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'NativeSwap',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'tokenOther',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'nativeAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'tokenAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'nativeIsInput',
        type: 'bool',
        indexed: false,
        internalType: 'bool'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'PriceImpactApplied',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'impactBps',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'deductedAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'SimpleSwap',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'tokenIn',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'amountOut',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'executionPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'TieredFeeApplied',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'volumeUSD',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'feeBps',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'feeAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'TwapSanityUpdated',
    inputs: [
      {
        name: 'enabled',
        type: 'bool',
        indexed: false,
        internalType: 'bool'
      },
      {
        name: 'period',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'maxDeviationBps',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'error',
    name: 'EnforcedPause',
    inputs: []
  },
  {
    type: 'error',
    name: 'ExpectedPause',
    inputs: []
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [
      {
        name: 'account',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'ReentrancyGuardReentrantCall',
    inputs: []
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ]
  }
] as const;
