// Auto-generated by paxeer-spot-integration-kit — DO NOT EDIT.
// Contract: PECORStopOrders
// Source:   ../../spot/out/PECORStopOrders.sol/PECORStopOrders.json

export const PECOR_STOP_ORDERS_ABI = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_priceOracle',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_vault',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_transactionTracker',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'BPS_DENOMINATOR',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'MAX_ORDER_FEE_BPS',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'accumulatedFees',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'activeStopLimitOrderIds',
    inputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'activeStopLossOrderIds',
    inputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'batchCheckAndExecuteStopLimits',
    inputs: [
      {
        name: 'orderIds',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    outputs: [
      {
        name: 'activatedCount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'executedCount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'batchExecuteStopLossOrders',
    inputs: [
      {
        name: 'orderIds',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    outputs: [
      {
        name: 'executedCount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'cancelStopLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'cancelStopLossOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'checkStopLimitActivation',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'collectFees',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'executeStopLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'executeStopLossOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'feeCollector',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'fillQualityTwapPeriod',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getAccumulatedFees',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getActivatableStopLimits',
    inputs: [
      {
        name: 'maxCount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderIds',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getActiveStopLimitOrderCount',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getActiveStopLossOrderCount',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getExecutableStopLimits',
    inputs: [
      {
        name: 'maxCount',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderIds',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getStopLimitOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct PECORStopOrders.StopLimitOrder',
        components: [
          {
            name: 'id',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'user',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'stablecoin',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'token',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'amount',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'stopPrice',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'limitPrice',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'orderType',
            type: 'uint8',
            internalType: 'enum PECORStopOrders.OrderType'
          },
          {
            name: 'status',
            type: 'uint8',
            internalType: 'enum PECORStopOrders.OrderStatus'
          },
          {
            name: 'createdAt',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'expiresAt',
            type: 'uint256',
            internalType: 'uint256'
          }
        ]
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getStopLossOrder',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct PECORStopOrders.StopLossOrder',
        components: [
          {
            name: 'id',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'user',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'stablecoin',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'token',
            type: 'address',
            internalType: 'address'
          },
          {
            name: 'amount',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'triggerPrice',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'status',
            type: 'uint8',
            internalType: 'enum PECORStopOrders.OrderStatus'
          },
          {
            name: 'createdAt',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'expiresAt',
            type: 'uint256',
            internalType: 'uint256'
          }
        ]
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getUserStopLimitOrders',
    inputs: [
      {
        name: 'user',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getUserStopLossOrders',
    inputs: [
      {
        name: 'user',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256[]',
        internalType: 'uint256[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'keepers',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'nextOrderId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'orderFeeBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'pause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'placeStopLimitBuy',
    inputs: [
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'stopPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'limitPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'placeStopLimitSell',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'stopPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'limitPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'placeStopLoss',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenAmount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'triggerPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'orderId',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'priceOracle',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPriceOracle'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setFeeCollector',
    inputs: [
      {
        name: '_collector',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setFillQualityTwapPeriod',
    inputs: [
      {
        name: 'period',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setKeeper',
    inputs: [
      {
        name: 'keeper',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'authorized',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setOrderFee',
    inputs: [
      {
        name: '_feeBps',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setPriceOracle',
    inputs: [
      {
        name: '_oracle',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setTransactionTracker',
    inputs: [
      {
        name: '_t',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'stopLimitOrders',
    inputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'user',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'stopPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'limitPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'orderType',
        type: 'uint8',
        internalType: 'enum PECORStopOrders.OrderType'
      },
      {
        name: 'status',
        type: 'uint8',
        internalType: 'enum PECORStopOrders.OrderStatus'
      },
      {
        name: 'createdAt',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'stopLossOrders',
    inputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'id',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'user',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'stablecoin',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amount',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'triggerPrice',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'status',
        type: 'uint8',
        internalType: 'enum PECORStopOrders.OrderStatus'
      },
      {
        name: 'createdAt',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'expiresAt',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'transactionTracker',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract ITransactionTracker'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      {
        name: 'newOwner',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'unpause',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'userStopLimitOrders',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'userStopLossOrders',
    inputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPECORVault'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'StopLimitActivated',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'activationPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'StopLimitCancelled',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'StopLimitExecuted',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'executionPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'StopLimitOrderCreated',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'orderType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PECORStopOrders.OrderType'
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'stopPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'limitPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'StopLossOrderCancelled',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'StopLossOrderCreated',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'triggerPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'StopLossOrderExecuted',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256'
      },
      {
        name: 'executionPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'error',
    name: 'CannotCancel',
    inputs: []
  },
  {
    type: 'error',
    name: 'EnforcedPause',
    inputs: []
  },
  {
    type: 'error',
    name: 'ExpectedPause',
    inputs: []
  },
  {
    type: 'error',
    name: 'FeeExceedsMax',
    inputs: []
  },
  {
    type: 'error',
    name: 'InsufficientLiquidity',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidExpiry',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidOracle',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidPrice',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidPrices',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidTWAPPeriod',
    inputs: []
  },
  {
    type: 'error',
    name: 'InvalidVault',
    inputs: []
  },
  {
    type: 'error',
    name: 'LimitMustBeAboveStopBuy',
    inputs: []
  },
  {
    type: 'error',
    name: 'LimitMustBeBelowStopSell',
    inputs: []
  },
  {
    type: 'error',
    name: 'NoFeesToCollect',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotAStablecoin',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotActivated',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotAuthorized',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotFeeCollector',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotOrderOwner',
    inputs: []
  },
  {
    type: 'error',
    name: 'NotPending',
    inputs: []
  },
  {
    type: 'error',
    name: 'OrderExpired',
    inputs: []
  },
  {
    type: 'error',
    name: 'OrderNotPending',
    inputs: []
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [
      {
        name: 'account',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'PriceAboveLimit',
    inputs: []
  },
  {
    type: 'error',
    name: 'PriceAboveTrigger',
    inputs: []
  },
  {
    type: 'error',
    name: 'PriceBelowLimit',
    inputs: []
  },
  {
    type: 'error',
    name: 'ReentrancyGuardReentrantCall',
    inputs: []
  },
  {
    type: 'error',
    name: 'TokenIsStablecoin',
    inputs: []
  },
  {
    type: 'error',
    name: 'TokenPaused',
    inputs: []
  },
  {
    type: 'error',
    name: 'ZeroAmount',
    inputs: []
  }
] as const;
