// Auto-generated by paxeer-spot-integration-kit — DO NOT EDIT.
// Contract: PriceOracleAdapter
// Source:   ../../spot/out/PriceOracleAdapter.sol/PriceOracleAdapter.json

export const PRICE_ORACLE_ADAPTER_ABI = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_priceOracle',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'CONFIDENCE_AGING',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'CONFIDENCE_FRESH',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'CONFIDENCE_NEAR_STALE',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'adapterName',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string'
      }
    ],
    stateMutability: 'pure'
  },
  {
    type: 'function',
    name: 'getFeedPrice',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: 'feed',
        type: 'tuple',
        internalType: 'struct IDataFeedAdapter.FeedPrice',
        components: [
          {
            name: 'price',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'timestamp',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'confidence',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'sourceId',
            type: 'bytes32',
            internalType: 'bytes32'
          }
        ]
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getFeedPrices',
    inputs: [
      {
        name: 'tokens',
        type: 'address[]',
        internalType: 'address[]'
      }
    ],
    outputs: [
      {
        name: 'feeds',
        type: 'tuple[]',
        internalType: 'struct IDataFeedAdapter.FeedPrice[]',
        components: [
          {
            name: 'price',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'timestamp',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'confidence',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'sourceId',
            type: 'bytes32',
            internalType: 'bytes32'
          }
        ]
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getSupportedTokens',
    inputs: [],
    outputs: [
      {
        name: 'tokens',
        type: 'address[]',
        internalType: 'address[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'maxStaleness',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'pure'
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'priceOracle',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPriceOracle'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setPriceOracle',
    inputs: [
      {
        name: '_oracle',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'sourceId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bytes32',
        internalType: 'bytes32'
      }
    ],
    stateMutability: 'pure'
  },
  {
    type: 'function',
    name: 'supportsToken',
    inputs: [
      {
        name: 'token',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      {
        name: 'newOwner',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'event',
    name: 'AdapterPriceServed',
    inputs: [
      {
        name: 'sourceId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32'
      },
      {
        name: 'token',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'price',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'confidence',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'AdapterRegistered',
    inputs: [
      {
        name: 'sourceId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32'
      },
      {
        name: 'adapter',
        type: 'address',
        indexed: true,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [
      {
        name: 'account',
        type: 'address',
        internalType: 'address'
      }
    ]
  }
] as const;
