// Auto-generated by paxeer-spot-integration-kit — DO NOT EDIT.
// Contract: VaultAdapter
// Source:   ../../spot/out/VaultAdapter.sol/VaultAdapter.json

export const VAULT_ADAPTER_ABI = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_vault',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_priceOracle',
        type: 'address',
        internalType: 'address'
      },
      {
        name: '_feeBps',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: '_feeCollector',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'BPS_DENOMINATOR',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'MAX_FEE_BPS',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'adapterId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bytes32',
        internalType: 'bytes32'
      }
    ],
    stateMutability: 'pure'
  },
  {
    type: 'function',
    name: 'adapterName',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string'
      }
    ],
    stateMutability: 'pure'
  },
  {
    type: 'function',
    name: 'adapterVersion',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
        internalType: 'string'
      }
    ],
    stateMutability: 'pure'
  },
  {
    type: 'function',
    name: 'executeSwap',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'minAmountOut',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: 'from',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'recipient',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'deadline',
        type: 'uint256',
        internalType: 'uint256'
      },
      {
        name: '',
        type: 'bytes',
        internalType: 'bytes'
      }
    ],
    outputs: [
      {
        name: 'result',
        type: 'tuple',
        internalType: 'struct IProtocolAdapter.SwapResult',
        components: [
          {
            name: 'amountOut',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'adapterData',
            type: 'bytes',
            internalType: 'bytes'
          }
        ]
      }
    ],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'feeBps',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'feeCollector',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getMaxInput',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: 'maxIn',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getQuote',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [
      {
        name: 'result',
        type: 'tuple',
        internalType: 'struct IProtocolAdapter.QuoteResult',
        components: [
          {
            name: 'amountOut',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'priceImpactBps',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'feeBps',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'feeAmount',
            type: 'uint256',
            internalType: 'uint256'
          },
          {
            name: 'available',
            type: 'bool',
            internalType: 'bool'
          },
          {
            name: 'adapterData',
            type: 'bytes',
            internalType: 'bytes'
          }
        ]
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'getSupportedPairs',
    inputs: [],
    outputs: [
      {
        name: 'tokenIns',
        type: 'address[]',
        internalType: 'address[]'
      },
      {
        name: 'tokenOuts',
        type: 'address[]',
        internalType: 'address[]'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'address'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'priceOracle',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPriceOracle'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setFee',
    inputs: [
      {
        name: '_feeBps',
        type: 'uint256',
        internalType: 'uint256'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setFeeCollector',
    inputs: [
      {
        name: '_collector',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'setPriceOracle',
    inputs: [
      {
        name: '_oracle',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'supportsSwap',
    inputs: [
      {
        name: 'tokenIn',
        type: 'address',
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
        internalType: 'bool'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      {
        name: 'newOwner',
        type: 'address',
        internalType: 'address'
      }
    ],
    outputs: [],
    stateMutability: 'nonpayable'
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPECORVault'
      }
    ],
    stateMutability: 'view'
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'event',
    name: 'SwapExecuted',
    inputs: [
      {
        name: 'adapterId',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32'
      },
      {
        name: 'tokenIn',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'tokenOut',
        type: 'address',
        indexed: true,
        internalType: 'address'
      },
      {
        name: 'amountIn',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'amountOut',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256'
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: false,
        internalType: 'address'
      }
    ],
    anonymous: false
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        internalType: 'address'
      }
    ]
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [
      {
        name: 'account',
        type: 'address',
        internalType: 'address'
      }
    ]
  }
] as const;
