// Code generated by tendermint/internal/protoutils/wireguard/plugin. DO NOT EDIT.
package statesync

import (
	wireguard "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/internal/protoutils/wireguard"
	utils "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/libs/utils"
	types "github.com/Sidiora-Labs/Paxeer-X-Network/consensus/proto/tendermint/types"
)

// SchemaForMessage is the wireguard.Schema generated for tendermint.statesync.Message.
var SchemaForMessage = &wireguard.Schema{
	Rules: map[wireguard.Number]wireguard.Rule{
		wireguard.MustFieldNum[Message_LightBlockResponse]("light_block_response"): {Nested: utils.Some(SchemaForLightBlockResponse)},
	},
}

// SchemaForLightBlockResponse is the wireguard.Schema generated for tendermint.statesync.LightBlockResponse.
var SchemaForLightBlockResponse = &wireguard.Schema{
	Rules: map[wireguard.Number]wireguard.Rule{
		wireguard.MustFieldNum[LightBlockResponse]("light_block"): {Nested: utils.Some(types.SchemaForLightBlock)},
	},
}

func (x *Message) WireguardScan(bz []byte) error {
	return SchemaForMessage.Scan(bz)
}

func (x *LightBlockResponse) WireguardScan(bz []byte) error {
	return SchemaForLightBlockResponse.Scan(bz)
}
