app = "paxeer-internal-redis"
primary_region = "ams"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[build]
  image = "redis:8.2.1-alpine"

[processes]
  app = "redis-server /run/secrets/redis.conf"

[[mounts]]
  source = "internal_redis_data"
  destination = "/data"
  initial_size = "2gb"
  snapshot_retention = 14

[[files]]
  guest_path = "/run/secrets/redis.conf"
  secret_name = "REDIS_CONF"

[[files]]
  guest_path = "/run/secrets/redis.crt"
  secret_name = "REDIS_TLS_CERT"

[[files]]
  guest_path = "/run/secrets/redis.key"
  secret_name = "REDIS_TLS_KEY"

[[files]]
  guest_path = "/run/secrets/ca.crt"
  secret_name = "REDIS_TLS_CA"

[[files]]
  guest_path = "/run/secrets/users.acl"
  secret_name = "REDIS_ACL"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpus = 1
  cpu_kind = "shared"
