[package]
name = "layerx-platform-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "layerx_platform_registry"
path = "src/lib.rs"

[[bin]]
name = "layerx-program-registry"
path = "src/main.rs"

[[bin]]
name = "layerx-cgroup-exec"
path = "src/bin/layerx-cgroup-exec.rs"

[dependencies]
layerx-client.workspace = true
layerx-crypto.workspace = true
layerx-types.workspace = true
nix = { version = "=0.29.0", features = ["user", "process", "fs"] }
layerx-platform-internal.workspace = true
layerx-programs = { package = "layerx-programs-registry", path = "../../../programs/crates/layerx-programs-registry" }
layerx-programs-protocol-adapter = { path = "../../../programs/crates/layerx-programs-protocol-adapter" }
layerx-proof.workspace = true
layerx-wire.workspace = true
serde_json.workspace = true
rustls.workspace = true
rustix.workspace = true
serde.workspace = true
sha2.workspace = true
subtle.workspace = true
openssl = "=0.10.81"
ureq.workspace = true
zeroize.workspace = true

[dev-dependencies]
native-tls.workspace = true
layerx-platform-gateway = { path = "../gateway" }
ed25519-dalek.workspace = true
layerx-programs-runtime = { path = "../../../programs/crates/layerx-programs-runtime" }

[lints]
workspace = true
