/**
 * Paxeer Network — Contract Addresses + Token Config
 * Auto-generated by scripts/generate-sdk.ts
 * Source: deployments/paxeer-addresses.json
 */

export const CHAIN_ID = 125 as const;
export const RPC_URL = "https://public-mainnet.rpcpaxeer.online/evm" as const;
export const EXPLORER_URL = "https://paxscan.io" as const;


// ─── V3 Core Contracts ────────────────────────────────────────────────────────
export const V3_CONTRACTS = {
    PriceOracle: "0xe7B20ef0bE7322D4B8d7E054e810b2209032750B",
    TransactionTracker: "0x7dACD66b913E427762c6FB35c57C5E52E860bc87",
    PECORVault: "0xDe5A8fc4396aE392957b547154B29b000D906a87",
    PECOR: "0x1AB090064857063bBB935cAe2b0FD2fE62F0d63B",
    PECOROrders: "0xE89a3E5dffEfbB7f8C9E9f597bbfd4F4ADE77404",
    PECORStopOrders: "0x49e2Fff129f9a351D94E3A25b2642Bfe37aCA912",
    PECORQuoter: "0x63b53724EC271799a7e2c9702072F12080F09e13",
} as const;

// ─── V4 Router Layer ──────────────────────────────────────────────────────────
export const V4_CONTRACTS = {
    OracleHub: "0x18DA624C9C5Ff17612EC5fC0A5070611053A180f",
    PriceOracleAdapter: "0x22C3D06F512ca59D9B523DB17ADB563fff68d065",
    SidioraFeedAdapter: "0x10A24fc47a2115389f251f72F444F61B3973434a",
    VaultAdapter: "0x66934c81c0E63b615264492aEB2988BC0f34b571",
    SidioraAdapter: "0x64967B75a8295d50D024415510B11a15049713d1",
    PECORRouter: "0x1D5f3ac9dE43Dd0665C3F527913dD825f67b3Daa",
} as const;

// ─── Sidiora Launchpad Protocol (external) ────────────────────────────────────
export const SIDIORA_CONTRACTS = {
    PoolRegistry: "0x1F22f11325197fae71937598F6935cc4e9231970",
    Quoter: "0xeDb3B45E320A8ab2306Fa1C303742f2478fd3E0a",
    Router: "0xB2D63300FE8b3508A83728e8f36B98e845eBD980",
} as const;

// Merged convenience alias
export const CONTRACTS = { ...V3_CONTRACTS, ...V4_CONTRACTS, ...SIDIORA_CONTRACTS } as const;

// ─── Tokens ───────────────────────────────────────────────────────────────────
export const TOKENS = {
    USDC: { address: "0xf8850b62AE017c55be7f571BBad840b4f3DA7D49", decimals: 6, symbol: "USDC", name: "USD Coin", isStablecoin: true },
    USDT: { address: "0x5dfE06Ae465a39c442c45ed273c523BaC2d1f6a8", decimals: 6, symbol: "USDT", name: "Tether USD", isStablecoin: true },
    USDL: { address: "0x7c69c84daAEe90B21eeCABDb8f0387897E9B7B37", decimals: 6, symbol: "USDL", name: "Liquidity USD", isStablecoin: true },
    USID: { address: "0x6C32c255EeBD6A72B56ee82454d7140020919652", decimals: 18, symbol: "USID", name: "USD Sidiora", isStablecoin: true },
    WPAX9: { address: "0xe5ccf339d1c89c7e6c6768b28507f78b861fc1de", decimals: 18, symbol: "WPAX9", name: "Wrapped PAX", isStablecoin: false },
    SID: { address: "0x86949e4CdB89496490890B67C9cfF63eD8efB4b1", decimals: 6, symbol: "SID", name: "Sidiora Markets", isStablecoin: false },
    WETH: { address: "0x5ba2f89F60f5805512A265bdFbB8984C85b4c9B7", decimals: 18, symbol: "WETH", name: "Wrapped ETH", isStablecoin: false },
    WBNB: { address: "0x2cE6495AF2F6cF20ea1b4d637dC2E882a0276F36", decimals: 18, symbol: "WBNB", name: "Wrapped BNB", isStablecoin: false },
    WUNI: { address: "0x2235fB5dFe619d67FcA1F9a70BD2B6725b13aE50", decimals: 18, symbol: "WUNI", name: "Wrapped UNI", isStablecoin: false },
    WSOL: { address: "0x38416f047c53C6D295AfF15e2fD296B6C896E2d8", decimals: 9, symbol: "WSOL", name: "Wrapped SOL", isStablecoin: false },
    WDOGE: { address: "0x7Bf5FFa044DC7789Bb3d71EA91d84a918a53a1F5", decimals: 8, symbol: "WDOGE", name: "Wrapped DOGE", isStablecoin: false },
    WBCH: { address: "0x9CcD709EB3460Dfb3ba62Ed5f1987A707a7Fbd59", decimals: 8, symbol: "WBCH", name: "Wrapped BCH", isStablecoin: false }
} as const;
export type TokenSymbol = keyof typeof TOKENS;

export const NATIVE_TOKEN = {
    address: "0x0000000000000000000000000000000000000000" as const,
    wrappedAddress: TOKENS.WPAX9.address,
    decimals: 18,
    symbol: "PAX",
    name: "Paxeer",
} as const;

export const TOKEN_LIST = Object.values(TOKENS);
export const STABLECOINS = TOKEN_LIST.filter(t => t.isStablecoin);
export const TRADE_TOKENS = TOKEN_LIST.filter(t => !t.isStablecoin);

export const MAX_UINT256 = BigInt("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
