/**
 * Paxeer SDK — React Hooks (Next.js compatible)
 * Auto-generated by scripts/generate-sdk.ts
 *
 * These are "vanilla" hooks with no external wallet-adapter dependency.
 * Pass your signer/provider from wagmi, RainbowKit, MetaMask, etc.
 */

"use client";

import { useState, useEffect, useCallback } from "react";
import { ethers } from "ethers";
import { getQuote, getPrice, getReserves } from "./pecor";
import { getPoolState, quoteBuy, quoteSell } from "./sidiora";
import type { QuoteResult, PoolState, SidioraQuoteResult } from "./types";

// ─── useSwapQuote ─────────────────────────────────────────────────────────────

interface UseSwapQuoteParams {
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    provider?: ethers.Provider;
}

export function useSwapQuote({ tokenIn, tokenOut, amountIn, provider }: UseSwapQuoteParams) {
    const [quote, setQuote] = useState<QuoteResult | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (!tokenIn || !tokenOut || amountIn === 0n) { setQuote(null); return; }
        let cancelled = false;
        setLoading(true);
        setError(null);
        getQuote(tokenIn, tokenOut, amountIn, provider)
            .then(q => { if (!cancelled) { setQuote(q); setLoading(false); } })
            .catch(e => { if (!cancelled) { setError(String(e)); setLoading(false); } });
        return () => { cancelled = true; };
    }, [tokenIn, tokenOut, amountIn.toString(), provider]);

    return { quote, loading, error };
}

// ─── useTokenPrice ────────────────────────────────────────────────────────────

export function useTokenPrice(tokenAddress: string, provider?: ethers.Provider) {
    const [price, setPrice] = useState<bigint | null>(null);
    const [stale, setStale] = useState(false);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (!tokenAddress) return;
        let cancelled = false;
        setLoading(true);
        getPrice(tokenAddress, provider)
            .then(({ price: p, stale: s }) => { if (!cancelled) { setPrice(p); setStale(s); setLoading(false); } })
            .catch(() => { if (!cancelled) setLoading(false); });
        return () => { cancelled = true; };
    }, [tokenAddress, provider]);

    return { price, stale, loading };
}

// ─── useVaultReserves ─────────────────────────────────────────────────────────

export function useVaultReserves(tokenAddress: string, provider?: ethers.Provider) {
    const [reserves, setReserves] = useState<bigint | null>(null);

    useEffect(() => {
        if (!tokenAddress) return;
        getReserves(tokenAddress, provider).then(setReserves).catch(() => { });
    }, [tokenAddress, provider]);

    return reserves;
}

// ─── useSidioraPool ───────────────────────────────────────────────────────────

export function useSidioraPool(poolAddress: string, provider?: ethers.Provider) {
    const [state, setState] = useState<PoolState | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const refresh = useCallback(() => {
        if (!poolAddress) return;
        setLoading(true);
        getPoolState(poolAddress, provider)
            .then(s => { setState(s); setLoading(false); })
            .catch(e => { setError(String(e)); setLoading(false); });
    }, [poolAddress, provider]);

    useEffect(() => { refresh(); }, [refresh]);

    return { state, loading, error, refresh };
}

// ─── useSidioraBuyQuote ───────────────────────────────────────────────────────

export function useSidioraBuyQuote(
    poolAddress: string,
    usdlAmountIn: bigint,
    provider?: ethers.Provider
) {
    const [quote, setQuote] = useState<SidioraQuoteResult | null>(null);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (!poolAddress || usdlAmountIn === 0n) { setQuote(null); return; }
        let cancelled = false;
        setLoading(true);
        quoteBuy(poolAddress, usdlAmountIn, provider)
            .then(q => { if (!cancelled) { setQuote(q); setLoading(false); } })
            .catch(() => { if (!cancelled) setLoading(false); });
        return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [poolAddress, usdlAmountIn.toString(), provider]);

    return { quote, loading };
}

// ─── useSidioraSellQuote ──────────────────────────────────────────────────────

export function useSidioraSellQuote(
    poolAddress: string,
    tokenAmountIn: bigint,
    provider?: ethers.Provider
) {
    const [quote, setQuote] = useState<SidioraQuoteResult | null>(null);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (!poolAddress || tokenAmountIn === 0n) { setQuote(null); return; }
        let cancelled = false;
        setLoading(true);
        quoteSell(poolAddress, tokenAmountIn, provider)
            .then(q => { if (!cancelled) { setQuote(q); setLoading(false); } })
            .catch(() => { if (!cancelled) setLoading(false); });
        return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [poolAddress, tokenAmountIn.toString(), provider]);

    return { quote, loading };
}
