// Code generated by scripts/bump_version; DO NOT EDIT.

package pointerview

import (
	pointerviewv552 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v552"
	pointerviewv555 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v555"
	pointerviewv562 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v562"
	pointerviewv605 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v605"
	pointerviewv606 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v606"
	pointerviewv610 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v610"
	pointerviewv614 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v614"
	pointerviewv620 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v620"
	pointerviewv630 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v630"
	pointerviewv640 "github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/pointerview/legacy/v640"
	"github.com/Sidiora-Labs/Paxeer-X-Network/precompiles/utils"
	"github.com/ethereum/go-ethereum/core/vm"
)

func GetVersioned(latestUpgrade string, keepers utils.Keepers) utils.VersionedPrecompiles {
	return utils.VersionedPrecompiles{
		latestUpgrade: check(NewPrecompile(keepers)),
		"v5.5.2":      check(pointerviewv552.NewPrecompile(keepers)),
		"v5.5.5":      check(pointerviewv555.NewPrecompile(keepers)),
		"v5.6.2":      check(pointerviewv562.NewPrecompile(keepers)),
		"v6.0.5":      check(pointerviewv605.NewPrecompile(keepers)),
		"v6.0.6":      check(pointerviewv606.NewPrecompile(keepers)),
		"v6.1.0":      check(pointerviewv610.NewPrecompile(keepers)),
		"v6.1.4":      check(pointerviewv614.NewPrecompile(keepers)),
		"v6.2.0":      check(pointerviewv620.NewPrecompile(keepers)),
		"v6.3.0":      check(pointerviewv630.NewPrecompile(keepers)),
		"v6.4.0":      check(pointerviewv640.NewPrecompile(keepers)),
	}
}

func check(p vm.PrecompiledContract, err error) vm.PrecompiledContract {
	if err != nil {
		panic(err)
	}
	return p
}
